[[redirects]]
  from = "/docs"
  to = "https://agilitycms-documentation-site.vercel.app/docs"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/docs/*"
  to = "https://agilitycms-documentation-site.vercel.app/docs/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}